import Brands from "@/components/Brands";
import Services from "@/components/Services";
import HeaderHero from "@/components/HeaderHero";
import Head from "next/head";
import About1 from "@/components/About1";
import About2 from "@/components/About2";
import About3 from "@/components/About3";
import About4 from "@/components/About4";
import Team from "@/components/Team";
import Testimonial from "@/components/Testimonial";
import BlogPosts from "@/components/BlogPosts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Basic - SaaS Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.webp" />
      </Head>
      <HeaderHero />
      <Brands />
      <Services />
      <About1 />
      <About2 />
      <About3 />
      <About4 />
      <Team />
      <Testimonial />
      <BlogPosts />
    </>
  );
}
