import Brands from "@/components/Brands";
import Features from "@/components/Features";
import HeaderHero from "@/components/HeaderHero";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Basic - SaaS Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.webp" />
      </Head>
      <HeaderHero />
      <Brands />
      <Features />
    </>
  );
}
